swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts:
    get:
      summary: Récupérer tous les comptes de l'utilisateur connecté
      tags:
        - Accounts
      security:
        - Bearer: []
      responses:
        200:
          description: List of accounts
          schema:
            type: array
            items:
              $ref: "#/definitions/Account"

  /account/transactions/accountId:
    get:
      summary: Récupérer tous les détails des transactions du mois en cours groupés par compte de l'utilisateur connecté
      tags:
        - Transactions
      security:
        - Bearer: []
      responses:
        200:
          description: List of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
    put:
      summary: Modifier les details de la transaction (categorie, note)
      tags:
        - Transactions
      security:
        - Bearer: []
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/TransactionInput"
      responses:
        200:
          description: Transaction updated
          schema:
            $ref: "#/definitions/Transaction"
        404:
          description: Transaction not found

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Account:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      amount:
        type: number

  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
        description: ID du compte auquel appartient la transaction
      accountName:
        type: string
        description: Nom du compte auquel appartient la transaction
      userId:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
      balance:
        type: number
        description: Solde du compte après la transaction
      type:
        type: string
        enum: [credit, debit]
      category:
        type: string
      note:
        type: string

  TransactionInput:
    type: object
    required:
      - date
      - amount
      - type
    properties:
      date:
        type: string
        format: date
      amount:
        type: number
      type:
        type: string
        enum: [credit, debit]
      category:
        type: string
      note:
        type: string

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

